#!/bin/bash
# Gateway startup: iptables policy, drop-log, DNS logger, then mitmweb.
# Packet capture lives in the netcap sidecar (inside the sandbox netns), not here:
# a capture on this side of the wire only sees traffic addressed to the gateway.
set -euo pipefail

INT_IP="172.30.0.2"
# index(...) == 1 is a literal prefix match, not a regex -- avoids "." in INT_IP
# being interpreted as "any character" (which would also match e.g. 172x30x0x2).
INT="$(ip -o -4 addr show | awk -v ip="$INT_IP" 'index($4, ip "/") == 1 {print $2}')"
EGR="$(ip -o -4 addr show | awk -v ifn="$INT" '$2 != "lo" && $2 != ifn {print $2}' | head -n1)"

if [ -z "$INT" ] || [ -z "$EGR" ]; then
  echo "FATAL: could not identify interfaces (internal='$INT' egress='$EGR')" >&2
  ip -o -4 addr show >&2
  exit 1
fi
echo "gateway: internal=$INT egress=$EGR"

mkdir -p /artifacts/mitm /artifacts/dns /gateway-ca

# Destinations mitmproxy must never be talked into fetching on the analyst's behalf.
# The sample only ever names a host; mitmproxy does the connecting, so without this
# the whole RFC1918 space, link-local, and the Docker host (host.docker.internal,
# 0.250.250.254 on OrbStack) are reachable through the proxy. Override with
# GATEWAY_BLOCKED_DESTS in .env (space-separated CIDRs) if a lab needs a private target.
GATEWAY_BLOCKED_DESTS="${GATEWAY_BLOCKED_DESTS:-10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 169.254.0.0/16 100.64.0.0/10 0.0.0.0/8 127.0.0.0/8}"

# --- iptables: fail closed. Nothing is forwarded; only mitmproxy/dnsmasq may be reached.
# Only flush PREROUTING (ours) in the nat table -- a full `-t nat -F` also wipes
# Docker's own DOCKER_OUTPUT/DOCKER_POSTROUTING chains and the OUTPUT jump to them,
# which is what makes the embedded resolver at 127.0.0.11 reachable from this container.
iptables -t nat -F PREROUTING
iptables -F
iptables -t nat -A PREROUTING -i "$INT" -p tcp --dport 80  -j REDIRECT --to-ports 8080
iptables -t nat -A PREROUTING -i "$INT" -p tcp --dport 443 -j REDIRECT --to-ports 8080
iptables -t nat -A PREROUTING -i "$INT" -p udp --dport 53  -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -i "$INT" -p tcp --dport 53  -j REDIRECT --to-ports 53
iptables -P FORWARD DROP
iptables -P INPUT DROP
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -i "$INT" -p tcp --dport 8080 -j ACCEPT
iptables -A INPUT -i "$INT" -p udp --dport 53 -j ACCEPT
iptables -A INPUT -i "$INT" -p tcp --dport 53 -j ACCEPT
iptables -A INPUT -i "$EGR" -p tcp --dport 8081 -j ACCEPT

# Egress destination blocklist. Scoped to -o $EGR so the gateway's own loopback
# traffic (including Docker's embedded resolver at 127.0.0.11) and the internal
# network are untouched. Replies on connections that were already accepted -- most
# importantly the analyst's mitmweb session arriving from the bridge gateway address,
# which itself sits in a blocked range -- are let through before the REJECTs.
iptables -A OUTPUT -o "$EGR" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
for cidr in $GATEWAY_BLOCKED_DESTS; do
  iptables -A OUTPUT -o "$EGR" -d "$cidr" -j REJECT --reject-with icmp-admin-prohibited
done

echo "gateway: iptables installed"
iptables -t nat -S PREROUTING
iptables -S INPUT
iptables -S OUTPUT

# --- DNS: every lookup from the sandbox is answered here and logged.
# --filter-AAAA: this gateway only intercepts IPv4 (no ip6tables rules, and the
# docker networks here have no IPv6 route out), so a real AAAA answer would either
# fail outbound or, worse, be an uncontrolled egress path around mitmproxy. Return
# NODATA for AAAA so clients fall back to the IPv4 address we actually intercept.
dnsmasq --keep-in-foreground --no-resolv --server=127.0.0.11 --filter-AAAA \
  --listen-address="$INT_IP" --bind-interfaces --no-hosts --cache-size=0 \
  --log-queries=extra --log-facility=/artifacts/dns/dns.log &

# --- The CA is generated by mitmproxy a moment after it starts; make it readable by
# uid 33 in the wordpress container as soon as it exists (the gateway_ca volume is
# mounted read-only there, so it cannot fix the mode itself).
(
  for _ in $(seq 1 120); do
    if [ -f /gateway-ca/mitmproxy-ca-cert.pem ]; then
      chmod 0644 /gateway-ca/mitmproxy-ca-cert.pem && exit 0
    fi
    sleep 1
  done
) &

# --- mitmweb in transparent mode. The CA lives in the gateway_ca volume so it is stable.
exec mitmweb \
  --mode transparent --showhost \
  --listen-host 0.0.0.0 --listen-port 8080 \
  --set web_host=0.0.0.0 --set web_port=8081 \
  --set web_password="${MITMWEB_PASSWORD:-sandbox}" \
  --set web_open_browser=false \
  --set ssl_insecure=true \
  --set confdir=/gateway-ca \
  -w +/artifacts/mitm/flows.mitm \
  ${MITM_EXTRA_ARGS:-}
